{
  parserClass="de.fabianholzwarth.brofian.mcfunction_lang.parser.McFunctionParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="McFunction"
  psiImplClassSuffix="Impl"
  psiPackage="de.fabianholzwarth.brofian.mcfunction_lang.psi"
  psiImplPackage="de.fabianholzwarth.brofian.mcfunction_lang.psi.impl"

  elementTypeHolderClass="de.fabianholzwarth.brofian.mcfunction_lang.psi.McFunctionTypes"
  elementTypeClass="de.fabianholzwarth.brofian.mcfunction_lang.psi.McFunctionElementType"
  tokenTypeClass="de.fabianholzwarth.brofian.mcfunction_lang.psi.McFunctionTokenType"

  psiImplUtilClass="de.fabianholzwarth.brofian.mcfunction_lang.psi.impl.McFunctionPsiImplUtil"
}

mcFunctionFile ::= line_*

line_ ::= (property|COMMENT|CRLF)

property ::= (COMMAND COORDINATE COORDINATE COORDINATE) | COMMAND | OPERATOR | COORDINATE | SELECTOR | IDENTIFIER  {
  mixin="de.fabianholzwarth.brofian.mcfunction_lang.psi.impl.McFunctionNamedElementImpl"
  implements="de.fabianholzwarth.brofian.mcfunction_lang.psi.McFunctionNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier]
}

